QnA/QnA/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path,include
from questions import views

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("questions/", include("questions.urls", namespace="questions")),
    path(
        "<str:model_name>/<int:object_id>/upvote",
        views.Upvote.as_view(),
        name="upvote",
    ),
    path(
        "<str:model_name>/<int:object_id>/downvote",
        views.Downvote.as_view(),
        name="downvote",
    ),
    path("", views.QuestionListView.as_view(), name="home"),
]

QnA/accounts/urls.py
from django.urls import path, include

from . import views

app_name = "accounts"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", views.signup, name="signup"),
]

QnA/questions/urls.py
from django.urls import path
from . import views

app_name = "questions"
urlpatterns = [
    path(
        "<int:pk>/", views.QuestionDetailView.as_view(), name="question_detail"
    ),
    path(
        "create-question/",
        views.QuestionCreateView.as_view(),
        name="create-question",
    ),
    path(
        "<int:pk>/edit",
        views.QuestionUpdateView.as_view(),
        name="edit-question",
    ),
    path(
        "<int:pk>/delete",
        views.QuestionDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<int:question_id>/create-answer",
        views.AnswerCreateView.as_view(),
        name="create-answer",
    ),
    path(
        "<int:question_id>/answers/<int:pk>/update-answer",
        views.AnswerUpdateView.as_view(),
        name="update-answer",
    ),
    path(
        "<int:question_id>/answers/<int:pk>/delete",
        views.AnswerDeleteView.as_view(),
        name="delete-answer",
    ),
    path(
        "<int:question_id>/comment/",
        views.CreateQuestionCommentView.as_view(),
        name="create_question_comment",
    ),
    path(
        "<int:question_id>/answers/<int:answer_id>/comment/",
        views.CreateAnswerCommentView.as_view(),
        name="create_answer_comment",
    ),
    path(
        "<int:question_id>/comments/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="delete-comment",
    ),
    path(
        "<int:question_id>/comment/<int:pk>/edit/",
        views.EditQuestionCommentView.as_view(),
        name="edit_question_comment",
    ),
    path(
        "<int:question_id>/answers/<int:answer_id>/comment/<int:pk>/edit/",
        views.EditAnswerCommentView.as_view(),
        name="edit_answer_comment",
    ),
]

QnA/templates/answer_confirm_delete.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Document</title>
</head>
<body class="bg-gray-100 p-10">
    <form method="post" class="bg-white align-center rounded-lg shadow w-6/12 h-36 mx-auto">{% csrf_token %}  
    <p class="py-5 px-6">Are you sure you want to delete this answer?</p>
    <a href="{% url 'questions:question_detail' object.id %}" class="inline-flex items-center px-6 py-3 ml-8 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-gray-100 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Cancel</a>
     <input type="submit" value="Confirm" class="inline-flex items-center px-6 py-3 ml-2 border border-red-200 text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 mt-3">
    </form>
</body>
</html>

QnA/templates/answer_update.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <div class="min-h-screen bg-gray-100 sm:px-6 lg:px-8">
        <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
          <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
            <form class="space-y-6" action="{%url 'questions:update-answer' answer.question.id answer.id %}" method="POST">
                <div class="sm:mx-auto sm:w-full sm:max-w-md">
                    <h2 class="mt-6 text-center text-3xl font-semibold text-gray-500">
                     {{answer.question.title}}
                    </h2>
                </div>
                {% for field in form %}
                    <div>
                        <label for="text" class="block text-sm font-medium text-gray-700">
                        {{field.label}}
                        </label>
                        {% render_field field class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="mt-2 text-sm text-red-600" id="error">{{error}}</p>
                        {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                {% csrf_token %}
              <div>
                <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Update
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
{% endblock %}

QnA/templates/base.html
{% load static %}
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}    
    <title>{% block title%}{% endblock %}</title>
</head>
<body class="bg-gray-100 w-screen h-screen">
<header class="bg-white">
    <div class="max-w-full lg:divide-y lg:divide-gray-200">
    <div class="px-6">
        <div class="relative h-16 flex justify-between">
        <div class="relative z-10 px-2 flex lg:px-0">
          <div class="flex-shrink-0 flex items-center">
            <a href="/">
              <img class="block h-10 w-auto" src="{% static 'img/stackicon.png' %}" alt="Workflow">
          </a>
        </div>
        </div>
        <div class="relative z-0 flex-1 px-2 flex items-center justify-center sm:absolute sm:inset-0">
          <nav class="hidden px-4 w-9/12 lg:py-2 lg:flex lg:space-x-8" aria-label="Global"> 
            <a href="/" class="border-b-4 border-yellow-300 font-semibold px-auto text-gray-900 py-5 px-3 inline-flex items-center text-sm font-medium">
              Questions
            </a>
          </nav>
        </div>

        <div class="hidden lg:relative lg:z-10 lg:ml-4 lg:flex lg:items-center space-x-2">
          {% if not user.is_authenticated %}
            <a href="{% url 'accounts:login' %}" class="inline-flex font-semibold items-center px-4 py-2 border border-gray-500 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-gray-200 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Login
            </a>
            <a href="{% url 'accounts:signup' %}" class="inline-flex items-center font-semibold px-4 py-2 border border-blue-700 shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Signup
            </a>
            {% else %}
            <a href="{% url 'accounts:logout' %}" class="inline-flex items-center px-4 py-2 border border-gray-500 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-gray-200 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Log out</a>
          {% endif %}
        </div>
      </div>
    </div >
</div> 
</div>
</header>

{% block detailbar%}
<div class="flex flex-row justify-between align-center mx-auto w-9/12 h-12 pb-8 pt-10"></div>
</div> 
{% endblock %}

    {% block body %}{% endblock %}
    {% block stylesheet %}{% endblock %}
</body>
</html>

QnA/templates/comment_confirm_delete.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Document</title>
</head>
<body class="bg-gray-100 p-10">
    <form method="post" class="bg-white align-center rounded-lg shadow w-6/12 h-36 mx-auto">{% csrf_token %}  
    <p class="py-5 px-6">Are you sure you want to delete this comment"?</p>
    <a href="{% url 'questions:question_detail' object.object_id %}" class="inline-flex items-center px-6 py-3 ml-8 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-gray-100 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Cancel</a>
     <input type="submit" value="Confirm" class="inline-flex items-center px-6 py-3 ml-2 border border-red-200 text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 mt-3">
    </form>
</body>
</html>

QnA/templates/comment_update.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <div class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
        <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
          <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
            <form class="space-y-6" method="POST">
                <div class="sm:mx-auto sm:w-full sm:max-w-md">
                    <h2 class="mt-6 text-center text-3xl font-semibold text-gray-500">
                     Question : {{question.title}}
                    </h2>
                    {% if answer %}
                    <p class="mt-6 text-center text-gray-500">
                        <span class="font-bold">Answer :</span> {{answer.text}}
                    </p>
                    {% endif %}
                </div>
                {% for field in form %}
                    <div>
                        <label for="text" class="block text-sm font-2xl font-bold text-gray-500 mb-3">
                        Your's Comment
                        </label>
                        {% render_field field class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="mt-2 text-sm text-red-600" id="error">{{error}}</p>
                        {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                {% csrf_token %}
              <div>
                <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Update
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
      {% endblock %}

QnA/templates/question_confirm_delete.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Document</title>
</head>
<body class="bg-gray-100 p-10">
    <form method="post" class="bg-white align-center rounded-lg shadow w-6/12 h-36 mx-auto">{% csrf_token %}  
    <p class="py-5 px-6">Are you sure you want to delete "{{ object.title }}"?</p>
    <a href="{% url 'questions:question_detail' object.id %}" class="inline-flex items-center px-6 py-3 ml-8 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-gray-100 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Cancel</a>
     <input type="submit" value="Confirm" class="inline-flex items-center px-6 py-3 ml-2 border border-red-200 text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 mt-3">
    </form>
</body>
</html>

QnA/templates/question_create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <div class="min-h-screen bg-gray-100 sm:px-6 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-md">
          <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
            
            <form class="space-y-4" action="{% url 'questions:create-question' %}" method="POST">
                <div class="sm:mx-auto sm:w-full sm:max-w-md">
                    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                      Create a Question
                    </h2>
                </div>
            {% for field in form %}
            <div>
                <label for="email" class="block text-sm font-medium text-gray-700">{{field.label}}</label>
                <div class="mt-1">
                    {% render_field field class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %} 
                </div>
                <p class="mt-2 text-sm text-gray-500" id="email-description">{{field.help_text}}</p>
                {% if field.errors %}
                {% for error in field.errors %}
                    <p class="mt-2 text-sm text-red-600" id="error">{{error}}</p>
                {% endfor %}
            {%endif%}
        </div>
            {% endfor %} 
            {% csrf_token %}
            <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Create
              </button> 
        </form>
        </div>       
    </div>       
</div>
{% endblock %}

QnA/templates/question_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Question list {% endblock %}
{% block detailbar%}
  <div class="flex justify-between w-9/12 align-center mx-auto mt-5">
    <span class="relative z-0 inline-flex shadow-sm rounded-md my-3">
    <a href="?order=-created" class="relative inline-flex items-center px-4 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
      Newest
    </a>
    <a href="?order=created" class="-ml-px relative inline-flex items-center rounded-r-md px-4 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500">
      oldest
    </a>
  </span>
  <a href="{% url 'questions:create-question' %}" class="inline-flex w-52 h-10 mt-2 mr-5 align-middle pl-12 font-semibold items-center px-3 tracking-wide  border border-gray-300 shadow-sm text-base font-medium rounded-md text-white bg-blue-500 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
    Ask Question
  </a>
 </div>
 {% endblock %}
{% block body %}
<main class="lg:col-span-9 xl:col-span-6 w-6xl">
    <div class="pt-4 bg-gray-100 h-max mx-auto">
      <h1 class="sr-only">Recent questions</h1>
      <ul role="list" class="space-y-4 pb-10 bg-gray-100 w-6xl h-5/6">
        {% for question in object_list %}
          <li class="bg-white w-9/12 mx-auto px-10 py-6 shadow sm:p-6 sm:rounded-lg flex justify-evenly">
            <div class="flex flex-col items-center w-10">             
              <a href="{% url 'upvote' "question" question.id %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 stroke-current text-gray-300 {% if question.vote.action == 0 %}text-blue-600{% endif %}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 11l3-3m0 0l3 3m-3-3v8m0-13a9 9 0 110 18 9 9 0 010-18z" />
                </svg>
              </a>
              <p>{{question.vote_score}}</p>
              <a href="{% url 'downvote' "question" question.id %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 stroke-current text-gray-300 {% if question.vote.action == 1 %}text-red-500{% endif %}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 13l-3 3m0 0l-3-3m3 3V8m0 13a9 9 0 110-18 9 9 0 010 18z" />
                </svg>
              </a>    
          </div>
      <article aria-labelledby="question-title-81614" class="w-11/12">
          <div>
            <div class="flex space-x-3">
              <div class="min-w-0 flex-1">
                <p class="text-xl font-semibold tracking-wide text-gray-800">
                  <a href="#" class="hover:underline">{{question.created_by.username}}</a>
                </p>
                <p class="text-sm text-gray-500">
                  <a href="#" class="hover:underline">
                    <time datetime="2020-12-09T11:43:00">{{question.created}}</time>
                  </a>
                </p>
              </div>
              <div class="flex-shrink-0 self-center flex">
                {% if question.created_by == user %}
                <div class="relative inline-block text-left">
                  <a href="{% url 'questions:edit-question' question.id %}" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    Edit
                  </a>
                  <a href="{% url 'questions:delete' question.id %}" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                    Delete
                  </a>
                </div>
                {% endif %}
              </div>
            </div>
            <a href="{% url 'questions:question_detail' question.id %}"><h2 id="question-title-81614" class="mt-4 text-base font-semibold text-blue-600">
                {{question.title}}
            </h2></a>
          </div>
          <div class="mt-2 text-sm text-gray-700 space-y-4">
            <p>{{question.description|truncatewords:50}}</p>
          </div>
          <div class="h-10">
            {% for tag in question.tags.all %}
            <a href="?tags={{tag}}"><span class="inline-flex items-center hover:bg-blue-500 font-bold tracking-wide mt-4 px-3 py-1.5 rounded text-xs font-medium bg-blue-400 text-white">
              {{tag}}
            </span></a>
            {%endfor%}
          </div>
          <div class="mt-6 flex justify-between space-x-8">
            <div class="flex space-x-6">
              <span class="inline-flex items-center text-sm">
                <a href="{% url 'questions:question_detail' question.id %}#comments" type="button" class="inline-flex space-x-2 text-gray-400 hover:text-gray-500">
                  <!-- Heroicon name: solid/chat-alt -->
                  <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z" clip-rule="evenodd" />
                  </svg>
                  <span class="font-medium text-gray-900">{{question.comments.count}}</span>
                  <span class="">comment{{question.comments.count|pluralize}}</span>
                </a>
              </span>
              <span class="inline-flex items-center text-sm">
                <a href="{% url 'questions:question_detail' question.id %}#answers" type="button" class="inline-flex space-x-2 text-gray-400 hover:text-gray-500">
                  <!-- Heroicon name: solid/eye -->
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                  </svg>
                  <span class="font-medium text-gray-900">{{question.answers.count}}</span>
                  <span class="">answer{{question.answers.count|pluralize}}</span>
                </button>
              </span>
            </div>
          </div>
        </article>
      </li>
    {% endfor %}
    </ul>
  </div>
  {% if is_paginated %}
  <nav class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6" aria-label="Pagination">
    <div class="-mt-px w-0 flex-1 flex">
      {% if page_obj.has_previous %}
      <a href="?page={{page_obj.previous_page_number}}" class="border-t-2 border-transparent pt-4 pr-1 inline-flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300">
        <svg class="mr-3 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd" />
        </svg>
        Previous
      </a>
      {%endif%}
    </div>
    
    <div class="md:-mt-px md:flex">
      {% for page_no in paginator.page_range %}
        <a href="?page={{page_no}}" class="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 border-t-2 pt-4 px-4 inline-flex items-center text-sm font-medium">
          {{page_no}}
        </a>
      {%endfor%}
    </div>
    
    <div class="-mt-px w-0 flex-1 flex justify-end">
      {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class="border-t-2 border-transparent pt-4 pl-1 inline-flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300">
          Next
          <svg class="ml-3 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
          </svg>
        </a>
    {% endif %}
  </div> 
  </nav>
  {% endif %}
</main>
{% endblock %}

QnA/templates/question_update.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <div class="min-h-screen bg-gray-100 sm:px-6 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-md">
          <div class="bg-white py-12 px-4 shadow sm:rounded-lg sm:px-10">
            
            <form class="space-y-4" action="{% url 'questions:edit-question' object.id %}" method="POST">
                <div class="sm:mx-auto sm:w-full sm:max-w-md">
                    <h2 class="text-center text-3xl font-extrabold text-gray-900">
                       Edit a Question
                    </h2>
                </div>
            {% for field in form %}
            <div>
                <label for="email" class="block text-sm font-medium text-gray-700">{{field.label}}</label>
                <div class="mt-1">
                    {% render_field field class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %} 
                </div>
                <p class="mt-2 text-sm text-gray-500" id="email-description">{{field.help_text}}</p>
                {% if field.errors %}
                {% for error in field.errors %}
                    <p class="mt-2 text-sm text-red-600" id="error">{{error}}</p>
                {% endfor %}
            {%endif%}
        </div>
            {% endfor %} 
            {% csrf_token %}
            <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Update
              </button> 
        </form>
        </div>       
    </div>       
</div>
{% endblock %}

QnA/templates/signup.html
{% load tailwind_tags %}
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %} 
    <title>Sign up</title>
</head>
<body>
    <div class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
        <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
          <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
            <form class="space-y-6" action="{% url 'accounts:signup' %}" method="POST">
                <div class="sm:mx-auto sm:w-full sm:max-w-md">
                    <img class="mx-auto h-12 w-auto" src="{% static 'img/stackicon.png' %}" alt="Workflow">
                    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                      Create an account
                    </h2>
                </div>
                {% for field in form %}
                    <div>
                        <label for="text" class="block text-sm font-medium text-gray-700">
                        {{field.label}}
                        </label>
                        {% render_field field class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %}
                        {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="mt-2 text-sm text-red-600" id="error">{{error}}</p>
                        {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                {% csrf_token %}
              <div>
                <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Sign up
                </button>
              </div>
            </form>
            <p class="mt-5 ml-16 font-semibold tracking-wide">Already have an account <a href="{% url 'accounts:login' %}" class="text-blue-800">Log in</a></p>
          </div>
        </div>
      </div>    
</body>
</html>